/**
 * Escalation policy — a declarative file deciding when Jarvis stops and asks Michael
 * instead of proceeding unattended, and a deterministic (non-LLM) decision module over it.
 *
 * With the human merge gate removed (spec § Two-Regime Model), Regime B runs to completion
 * and merges on its own. That makes one question load-bearing: **when does Jarvis escalate
 * to the blocked-on-Michael state (Layer 3) rather than proceed?** The answer is this
 * policy — the same shape as the model selection policy: data not code, editing it is not
 * a deploy.
 *
 * The policy enumerates rules across the four escalation conditions from the spec:
 *   1. a class of change too high-risk to merge unattended      (`high-risk-change-class`)
 *   2. a cross-model review the Evaluator cannot resolve        (`unresolvable-cross-model-review`)
 *   3. a run that exceeds its bounds                            (`run-exceeded-bounds`)
 *   4. a self-generated spec too consequential to approve       (`consequential-self-generated-spec`)
 *
 * The specific rules are deliberately left to fill in over time; what is pinned here is the
 * mechanism — escalation is policy-driven, deterministic, and auditable, never ad hoc.
 *
 * STATUS: partially implemented. `parseEscalationPolicy` validates the declarative policy
 * file (`policies/escalation-policy.json`). `decide` and `decideFailClosed` remain contract
 * stubs, filled in by the Phase 1 escalation decision-module task; their tests in
 * `escalation.test.ts` (test-plan.md §6) stay RED until then.
 *
 * See docs/projects/08-intent-layer/{spec.md (§"Escalation policy"), test-plan.md (§6)}.
 */

/** The blocked-on-Michael state (Layer 3) vs. proceeding unattended. */
export type EscalationVerdict = 'escalate' | 'proceed';

/** The four escalation conditions from the spec — the dimensions a rule can match on. */
export type EscalationCondition =
  /** A class of change too high-risk to merge unattended (e.g. auth, migrations, credentials). */
  | 'high-risk-change-class'
  /** A cross-model review the Evaluator cannot bring to a resolved verdict. */
  | 'unresolvable-cross-model-review'
  /** A run that exceeds its bounds (e.g. too many Evaluator rounds). */
  | 'run-exceeded-bounds'
  /** A self-generated spec too consequential to approve without Michael. */
  | 'consequential-self-generated-spec';

/**
 * One declarative escalation rule — data, not code. Adding or changing a rule is an edit
 * to the policy file, never a deploy. Each rule belongs to exactly one escalation
 * condition; the per-condition matcher fields below are required only for the conditions
 * that need parameters.
 */
export interface EscalationRule {
  /** Stable identifier, surfaced verbatim in the audit log when the rule fires. */
  id: string;
  /** Which of the four escalation conditions this rule belongs to. */
  condition: EscalationCondition;
  /**
   * `high-risk-change-class` only — glob patterns over changed repo-relative paths. A
   * changed path matching any pattern fires the rule. Required for that condition.
   */
  pathPatterns?: string[];
  /**
   * `run-exceeded-bounds` only — the run escalates once its Evaluator rounds exceed this
   * count. Required for that condition.
   */
  maxEvaluatorRounds?: number;
}

/** The declarative escalation policy — a versioned list of rules. */
export interface EscalationPolicy {
  /** Schema version, for forward-compatible reads. */
  version: number;
  /** The escalation rules. An empty list is valid — it means nothing ever escalates. */
  rules: EscalationRule[];
}

/**
 * The change being weighed for escalation. Every field is optional: a given decision point
 * only carries the dimensions relevant to it (a spec-approval check has no `evaluatorRounds`
 * yet; a pre-merge check has no `specOrigin`). A rule only fires when its condition's
 * dimension is present and matches.
 */
export interface ChangeContext {
  /** Repo-relative paths the change touches — matched against `high-risk-change-class` rules. */
  changedPaths?: string[];
  /** Cross-model review outcome: `unresolved` when the Evaluator could not reach a verdict. */
  crossModelReview?: 'resolved' | 'unresolved';
  /** Evaluator rounds the Generator-Evaluator loop has consumed so far. */
  evaluatorRounds?: number;
  /** Whether the spec was self-generated by the observation loop, or human-authored. */
  specOrigin?: 'human' | 'self-generated';
  /** Coarse consequence rating of a self-generated spec. */
  specConsequence?: 'routine' | 'consequential';
}

/**
 * The outcome of a decision — the escalate/proceed verdict and, when escalating, the rule
 * and condition that fired. Consumed by the supervision visibility surface (§10) and the
 * cockpit, which render an `escalate` verdict as blocked-on-Michael.
 */
export interface EscalationDecision {
  /** `escalate` = enter the blocked-on-Michael state; `proceed` = run unattended. */
  verdict: EscalationVerdict;
  /** The escalation condition that fired. Set only when `verdict` is `escalate`. */
  condition?: EscalationCondition;
  /** The id of the specific rule that fired. Set only when `verdict` is `escalate`. */
  ruleId?: string;
  /** Human-readable reason — surfaced by supervision (§10) and the cockpit. */
  reason: string;
  /**
   * True when the verdict is `escalate` because the policy itself was missing or malformed
   * (the fail-closed path) rather than because a rule matched. Never set on a `proceed`.
   */
  failClosed?: boolean;
}

const NOT_IMPLEMENTED =
  'escalation: not implemented — Phase 1 escalation-policy tasks (docs/projects/08-intent-layer) fill this in';

/** The four escalation conditions the policy understands. */
const ESCALATION_CONDITIONS = new Set<EscalationCondition>([
  'high-risk-change-class',
  'unresolvable-cross-model-review',
  'run-exceeded-bounds',
  'consequential-self-generated-spec',
]);

/** Validate one raw rule into an `EscalationRule`, throwing a clear, indexed error. */
function parseEscalationRule(value: unknown, index: number): EscalationRule {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new Error(`escalation policy is invalid — rules[${index}] is not an object`);
  }
  const r = value as Record<string, unknown>;
  if (typeof r['id'] !== 'string' || r['id'] === '') {
    throw new Error(`escalation policy is invalid — rules[${index}].id is missing or not a string`);
  }
  const condition = r['condition'];
  if (typeof condition !== 'string' || !ESCALATION_CONDITIONS.has(condition as EscalationCondition)) {
    throw new Error(
      `escalation policy is invalid — rules[${index}].condition is missing or unknown ` +
        `(expected one of ${[...ESCALATION_CONDITIONS].join(', ')})`,
    );
  }
  const rule: EscalationRule = { id: r['id'], condition: condition as EscalationCondition };

  // A high-risk-change-class rule needs the path globs it matches against.
  if (condition === 'high-risk-change-class') {
    const patterns = r['pathPatterns'];
    if (
      !Array.isArray(patterns) ||
      patterns.length === 0 ||
      !patterns.every((p) => typeof p === 'string')
    ) {
      throw new Error(
        `escalation policy is invalid — rules[${index}] (high-risk-change-class) requires ` +
          'a non-empty pathPatterns string array',
      );
    }
    rule.pathPatterns = patterns as string[];
  }

  // A run-exceeded-bounds rule needs the Evaluator-round cap it compares against. A cap of
  // zero or below is a misconfiguration (it would escalate every run) — reject it.
  if (condition === 'run-exceeded-bounds') {
    const cap = r['maxEvaluatorRounds'];
    if (typeof cap !== 'number' || !Number.isInteger(cap) || cap <= 0) {
      throw new Error(
        `escalation policy is invalid — rules[${index}] (run-exceeded-bounds) requires ` +
          'a positive-integer maxEvaluatorRounds',
      );
    }
    rule.maxEvaluatorRounds = cap;
  }

  return rule;
}

/**
 * Parse and validate an escalation policy from its declarative file content. Throws a
 * clear error — fast, at load time — when the content is malformed or structurally
 * invalid; a broken policy is never silently replaced with an empty (permissive) one.
 *
 * Validation covers: valid JSON; a numeric `version`; `rules` is an array; every rule has
 * a string `id` and a `condition` that is one of the four known values; a
 * `high-risk-change-class` rule carries a non-empty `pathPatterns`; a `run-exceeded-bounds`
 * rule carries a positive-integer `maxEvaluatorRounds`.
 */
export function parseEscalationPolicy(raw: string): EscalationPolicy {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new Error(`escalation policy is malformed — could not parse: ${(err as Error).message}`);
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('escalation policy is malformed — expected a JSON object');
  }
  const p = parsed as Record<string, unknown>;

  const version = p['version'];
  if (typeof version !== 'number') {
    throw new Error('escalation policy is invalid — `version` is missing or not a number');
  }
  if (!Array.isArray(p['rules'])) {
    throw new Error('escalation policy is invalid — `rules` must be an array');
  }
  const rules = p['rules'].map((rule, index) => parseEscalationRule(rule, index));
  return { version, rules };
}

/**
 * Deterministically decide escalate/proceed for a change — no LLM call, no I/O, pure over
 * `(change, policy)`. Every rule in the policy is evaluated against the change; the verdict
 * is `escalate` if any rule fires, `proceed` if none does. When multiple rules fire, the
 * first in policy order determines `condition` and `ruleId` — the verdict is `escalate`
 * regardless. Every decision is logged; an escalation is logged with the firing rule's id
 * and condition so it is auditable.
 */
export function decide(_change: ChangeContext, _policy: EscalationPolicy): EscalationDecision {
  throw new Error(NOT_IMPLEMENTED);
}

/**
 * The fail-closed entry point the engine calls: load the policy from its raw file content
 * and decide. A `null` (missing) or unparseable policy **fails closed** — it returns an
 * `escalate` decision with `failClosed: true`, logged, and never a `proceed`. The engine
 * must never fall open to permissive auto-merge when the policy is unavailable. With a
 * valid policy this delegates to {@link decide}.
 */
export function decideFailClosed(
  _change: ChangeContext,
  _rawPolicy: string | null,
): EscalationDecision {
  throw new Error(NOT_IMPLEMENTED);
}
